const categories=["食事量改善","栄養バランス改善","活動量UP","ボディメイク","睡眠改善","ストレスケア","環境づくり","継続の工夫"];
const questions=[
{id:"age",title:"年齢を選んでください",help:"近いものを選んでください。",type:"single",options:["18歳未満","18〜29歳","30〜39歳","40〜49歳","50歳以上"],score:{}},
{id:"height",title:"身長を入力してください",help:"BMI判定に使用します。",type:"number",unit:"cm",score:{}},
{id:"weight",title:"現在の体重を入力してください",help:"BMI判定に使用します。",type:"number",unit:"kg",score:{}},
{id:"goalWeight",title:"目標体重を入力してください",help:"今の目標でOKです。",type:"number",unit:"kg",score:{}},
{id:"goal",title:"今一番叶えたいことは？",help:"今の気持ちに一番近いものを選んでください。",type:"single",options:["体重を落としたい","見た目を変えたい","健康になりたい","リバウンドしない身体を作りたい","まだ分からない"],score:{}},
{id:"worry",title:"今一番悩んでいることは？",help:"最大2つまで選べます。",type:"multi",max:2,options:["体重","体脂肪","下腹","下半身","姿勢","肩こり・腰痛","リバウンド","健康"],score:{"体重":{"食事量改善":3},"体脂肪":{"食事量改善":3,"活動量UP":2},"下腹":{"ボディメイク":6},"下半身":{"ボディメイク":6},"姿勢":{"ボディメイク":7},"肩こり・腰痛":{"ボディメイク":5},"リバウンド":{"継続の工夫":6}}},
{id:"state",title:"今の自分に一番近いものは？",help:"診断結果の方向性に反映します。",type:"single",options:["何から始めたらいいか分からない","頑張っているのに痩せない","続かない","リバウンドを繰り返している","体重より見た目を変えたい"],score:{"何から始めたらいいか分からない":{"継続の工夫":6},"頑張っているのに痩せない":{"栄養バランス改善":4,"活動量UP":4},"続かない":{"継続の工夫":8},"リバウンドを繰り返している":{"継続の工夫":8,"食事量改善":3},"体重より見た目を変えたい":{"ボディメイク":8}}},
{id:"full",title:"満腹になるまで食べることが多いですか？",help:"食事量の優先度を判定します。",type:"single",options:["毎回","よくある","時々","ほとんどない"],score:{"毎回":{"食事量改善":10},"よくある":{"食事量改善":8},"時々":{"食事量改善":4}}},
{id:"notHungry",title:"空腹ではないのに食べることがありますか？",help:"間食やストレス食いの傾向を見ます。",type:"single",options:["よくある","時々","ほとんどない"],score:{"よくある":{"食事量改善":8,"ストレスケア":2},"時々":{"食事量改善":4,"ストレスケア":1}}},
{id:"snack",title:"間食はどのくらいしますか？",help:"ダイエット中でも間食は悪ではありません。頻度を見ます。",type:"single",options:["1日2回以上","1日1回","週2〜3回","ほとんどしない"],score:{"1日2回以上":{"食事量改善":10},"1日1回":{"食事量改善":6},"週2〜3回":{"食事量改善":3}}},
{id:"drink",title:"甘い飲み物を飲みますか？",help:"カフェラテやジュースなども含みます。",type:"single",options:["毎日","週3〜5回","週1〜2回","ほとんど飲まない"],score:{"毎日":{"食事量改善":8},"週3〜5回":{"食事量改善":5},"週1〜2回":{"食事量改善":2}}},
{id:"night",title:"夜21時以降に食事をすることがありますか？",help:"生活リズムに合わせて判定します。",type:"single",options:["ほぼ毎日","週3〜5回","週1〜2回","ほとんどない"],score:{"ほぼ毎日":{"食事量改善":6,"環境づくり":3},"週3〜5回":{"食事量改善":4,"環境づくり":2},"週1〜2回":{"食事量改善":2}}},
{id:"speed",title:"食べるスピードは？",help:"早食いは満腹感に影響しやすいです。",type:"single",options:["10分以内","10〜20分","20分以上"],score:{"10分以内":{"食事量改善":6},"10〜20分":{"食事量改善":2}}},
{id:"protein",title:"毎食たんぱく質を食べていますか？",help:"肉・魚・卵・大豆製品・乳製品など。",type:"single",options:["ほとんど食べない","1食だけ","2食","3食"],score:{"ほとんど食べない":{"栄養バランス改善":10},"1食だけ":{"栄養バランス改善":6},"2食":{"栄養バランス改善":2}}},
{id:"vege",title:"野菜・きのこ・海藻類を食べていますか？",help:"毎食完璧でなくてOKです。",type:"single",options:["ほとんど食べない","1食だけ","2食","3食以上"],score:{"ほとんど食べない":{"栄養バランス改善":8},"1食だけ":{"栄養バランス改善":5},"2食":{"栄養バランス改善":2}}},
{id:"water",title:"水分は1日どのくらい飲みますか？",help:"水・お茶などを目安にしてください。",type:"single",options:["1L未満","1〜1.5L","1.5L以上"],score:{"1L未満":{"栄養バランス改善":6},"1〜1.5L":{"栄養バランス改善":3}}},
{id:"breakfast",title:"朝食を食べていますか？",help:"固定化できると続けやすくなります。",type:"single",options:["ほとんど食べない","食べたり食べなかったり","毎日食べる"],score:{"ほとんど食べない":{"栄養バランス改善":5,"環境づくり":2},"食べたり食べなかったり":{"栄養バランス改善":3}}},
{id:"outside",title:"外食・コンビニを利用する頻度は？",help:"多いほど環境づくりが大切になります。",type:"single",options:["ほぼ毎日","週3〜5回","週1〜2回","ほとんどない"],score:{"ほぼ毎日":{"環境づくり":6,"栄養バランス改善":4},"週3〜5回":{"環境づくり":4,"栄養バランス改善":2}}},
{id:"steps",title:"平均歩数はどのくらいですか？",help:"だいたいでOKです。",type:"single",options:["1000歩未満","3000歩未満","5000歩未満","8000歩以上"],score:{"1000歩未満":{"活動量UP":10},"3000歩未満":{"活動量UP":8},"5000歩未満":{"活動量UP":5}}},
{id:"work",title:"仕事や日中の過ごし方は？",help:"日常活動量を判定します。",type:"single",options:["座っている時間が長い","立ち仕事が多い","半々くらい","よく動く"],score:{"座っている時間が長い":{"活動量UP":6},"半々くらい":{"活動量UP":2}}},
{id:"exerciseReason",title:"運動できない理由に近いものは？",help:"責めるためではなく、続け方を見つけるための質問です。",type:"single",options:["時間がない","苦手","続かない","何をしたらいいか分からない","必要性を感じない"],score:{"時間がない":{"活動量UP":4,"環境づくり":6},"苦手":{"活動量UP":6,"継続の工夫":3},"続かない":{"活動量UP":4,"継続の工夫":6},"何をしたらいいか分からない":{"活動量UP":5,"継続の工夫":5},"必要性を感じない":{"活動量UP":3}}},
{id:"bodySatisfaction",title:"現在の体重には満足していますか？",help:"現在地判定にも使います。",type:"single",options:["満足","少し不満","かなり不満"],score:{"少し不満":{"食事量改善":3},"かなり不満":{"食事量改善":6}}},
{id:"parts",title:"見た目で気になる部位は？",help:"最大3つまで選べます。",type:"multi",max:3,options:["下腹","下半身","お尻","二の腕","背中","姿勢","顔"],score:{"下腹":{"ボディメイク":7},"下半身":{"ボディメイク":7},"お尻":{"ボディメイク":6},"二の腕":{"ボディメイク":5},"背中":{"ボディメイク":5},"姿勢":{"ボディメイク":7},"顔":{"食事量改善":2}}},
{id:"posture",title:"姿勢で気になることは？",help:"分からない場合は『分からない』でOKです。",type:"multi",max:3,options:["反り腰","猫背","巻き肩","ストレートネック","分からない","特になし"],score:{"反り腰":{"ボディメイク":8},"猫背":{"ボディメイク":6},"巻き肩":{"ボディメイク":6},"ストレートネック":{"ボディメイク":5},"分からない":{"ボディメイク":2}}},
{id:"condition",title:"身体の不調はありますか？",help:"最大3つまで選べます。",type:"multi",max:3,options:["肩こり","腰痛","むくみ","冷え","特になし"],score:{"肩こり":{"ボディメイク":4,"ストレスケア":2},"腰痛":{"ボディメイク":5},"むくみ":{"活動量UP":3,"栄養バランス改善":2},"冷え":{"活動量UP":2,"栄養バランス改善":2}}},
{id:"sleep",title:"平均睡眠時間は？",help:"睡眠は食欲や継続力にも影響します。",type:"single",options:["5時間未満","5〜6時間","6〜7時間","7時間以上"],score:{"5時間未満":{"睡眠改善":10},"5〜6時間":{"睡眠改善":6},"6〜7時間":{"睡眠改善":3}}},
{id:"sleepReason",title:"睡眠不足の理由に近いものは？",help:"一番近いものを選んでください。",type:"single",options:["仕事","育児","スマホ","夜更かし","その他"],score:{"仕事":{"睡眠改善":6,"環境づくり":6},"育児":{"睡眠改善":6,"環境づくり":8,"ストレスケア":2},"スマホ":{"睡眠改善":8,"継続の工夫":2},"夜更かし":{"睡眠改善":8,"継続の工夫":2},"その他":{"睡眠改善":4}}},
{id:"stressEat",title:"ストレスで食べてしまうことがありますか？",help:"ストレスと食事の関係を見ます。",type:"single",options:["よくある","時々","ほとんどない"],score:{"よくある":{"ストレスケア":8,"食事量改善":4},"時々":{"ストレスケア":4,"食事量改善":2}}},
{id:"stress",title:"最近ストレスを感じていますか？",help:"ダイエットの前に整えるべきことが見える場合があります。",type:"single",options:["強く感じる","少し感じる","あまり感じない"],score:{"強く感じる":{"ストレスケア":8},"少し感じる":{"ストレスケア":4}}},
{id:"relax",title:"リラックスできる時間はありますか？",help:"短時間でもOKです。",type:"single",options:["ほとんどない","少しある","十分ある"],score:{"ほとんどない":{"ストレスケア":7,"環境づくり":3},"少しある":{"ストレスケア":3}}},
{id:"familyMeal",title:"家族と別メニューは作れますか？",help:"作れない場合も、続け方を工夫できます。",type:"single",options:["作れない","時々ならできる","作れる","一人暮らし"],score:{"作れない":{"環境づくり":8},"時々ならできる":{"環境づくり":4}}},
{id:"freeTime",title:"自由に使える時間はどのくらいありますか？",help:"日々のダイエットに使える時間です。",type:"single",options:["30分未満","30〜60分","1時間以上"],score:{"30分未満":{"環境づくり":8},"30〜60分":{"環境づくり":4}}},
{id:"busy",title:"今の生活で一番忙しい理由は？",help:"無理なく続ける方法を見つけます。",type:"single",options:["仕事","育児","介護","家事","その他"],score:{"仕事":{"環境づくり":6},"育児":{"環境づくり":8,"ストレスケア":2},"介護":{"環境づくり":8,"ストレスケア":3},"家事":{"環境づくり":5}}},
{id:"fail",title:"ダイエットが続かなかった一番の理由は？",help:"過去の失敗は、次に続けるヒントになります。",type:"single",options:["時間がなかった","モチベーションが続かなかった","我慢できなかった","結果が出なかった","方法が分からなかった"],score:{"時間がなかった":{"環境づくり":6,"継続の工夫":4},"モチベーションが続かなかった":{"継続の工夫":8},"我慢できなかった":{"食事量改善":4,"継続の工夫":5},"結果が出なかった":{"継続の工夫":8},"方法が分からなかった":{"継続の工夫":6}}},
{id:"support",title:"どんなサポートがあると続けられそうですか？",help:"今後の行動のヒントにします。",type:"single",options:["一人でコツコツ","仲間がほしい","記録したい","専門家に相談したい","分からない"],score:{"仲間がほしい":{"継続の工夫":4},"記録したい":{"継続の工夫":2},"専門家に相談したい":{"継続の工夫":3},"分からない":{"継続の工夫":5}}}
];
const templates={"食事量改善":{why:"食事量や間食、飲み物などから摂るエネルギーを少し整えることで、変化が出やすい状態です。まずは食事を大きく変えるより、量やタイミングを整えることから始めましょう。",actions:["食事記録を3日だけつける","腹八分目を意識する","甘い飲み物を1日1杯お茶や水に変える"],change:["体重の変化を感じやすくなる","食べ過ぎのクセに気づける","無理な制限をしなくて済む"],message:"全部変えようとしなくて大丈夫。まずは食事量を少し整えることから始めてみましょう。"},"栄養バランス改善":{why:"食事量を減らすことよりも、たんぱく質・野菜・水分などを整えることが優先です。栄養が整うと、満足感や身体づくりにもつながります。",actions:["毎食たんぱく質を1つ入れる","野菜・きのこ・海藻を1品追加する","水分をこまめに飲む"],change:["満足感が増えやすい","筋肉を守りながら痩せやすい","体調が整いやすい"],message:"減らすより、まず整える。栄養バランスを味方につけましょう。"},"活動量UP":{why:"今は激しい運動より、日常生活で動く量を増やすことが変化につながりやすい状態です。まずは歩く・立つ・階段を使うなど、小さな活動量から増やしましょう。",actions:["今より＋2000歩を目指す","30分に1回立ち上がる","近い距離は歩く"],change:["消費エネルギーが増える","むくみが改善しやすい","運動へのハードルが下がる"],message:"運動が苦手でも大丈夫。まずは“生活の中で動く”から始めましょう。"},"ボディメイク":{why:"体重を落とすことだけでなく、姿勢や筋肉を整えることで理想の見た目に近づきやすい状態です。",actions:["気になる部位の宅トレを週2回","ストレッチを5分","ピラティスや姿勢改善を取り入れる"],change:["シルエットが整いやすい","姿勢がきれいに見えやすい","体重以外の変化を感じやすい"],message:"体重だけが正解ではありません。見た目を整える身体づくりも大切なダイエットです。"},"睡眠改善":{why:"睡眠不足は食欲や疲労感にも影響します。時間を大きく増やせなくても、睡眠の質や生活リズムを整える工夫が大切です。",actions:["30分だけ早く寝る日を作る","寝る前のスマホ時間を短くする","朝日を浴びる"],change:["食欲が安定しやすい","疲れにくくなる","日中の活動量が上がりやすい"],message:"忙しくても、できる範囲で睡眠を整えることはダイエットの土台になります。"},"ストレスケア":{why:"ストレスは食欲の増加や睡眠の質の低下につながり、ダイエットにも影響を与えることがあります。まずは自分に合うストレス発散方法を見つけましょう。",actions:["ウォーキングや軽い運動をする","ヨガ・瞑想・深呼吸を試す","趣味やリラックス時間を作る"],change:["ストレス食いが減りやすい","睡眠が整いやすい","継続しやすくなる"],message:"頑張り続けるだけが正解ではありません。ストレスを上手に発散することも、健康的なダイエットの一部です。"},"環境づくり":{why:"今の生活では、気合いで頑張るよりも続けやすい環境を作ることが優先です。忙しい毎日でもできる仕組みに変えていきましょう。",actions:["朝食を固定化する","コンビニ・冷凍食品も活用する","家族と同じメニューで量を調整する"],change:["迷う時間が減る","忙しくても続けやすい","リバウンドしにくい仕組みができる"],message:"もっと頑張るより、続く仕組みを作ることが近道です。"},"継続の工夫":{why:"方法そのものより、続け方を整えることで成功しやすい状態です。完璧を目指さず、小さく続ける設計にしましょう。",actions:["今週やることを3つに絞る","できたことを記録する","完璧ではなく再開を目標にする"],change:["挫折しにくくなる","自己嫌悪が減る","習慣として続きやすい"],message:"続かないのは意志が弱いからではありません。続く仕組みに変えていきましょう。"}};
let current=0,answers={};
const startScreen=document.getElementById("startScreen"),quizScreen=document.getElementById("quizScreen"),resultScreen=document.getElementById("resultScreen"),questionTitle=document.getElementById("questionTitle"),questionHelp=document.getElementById("questionHelp"),answerArea=document.getElementById("answerArea"),progressText=document.getElementById("progressText"),progressBar=document.getElementById("progressBar");
document.getElementById("startBtn").addEventListener("click",()=>{startScreen.classList.remove("active");quizScreen.classList.add("active");renderQuestion()});
document.getElementById("backBtn").addEventListener("click",()=>{if(current>0){current--;renderQuestion()}else{quizScreen.classList.remove("active");startScreen.classList.add("active")}});
document.getElementById("nextBtn").addEventListener("click",()=>{const q=questions[current],value=answers[q.id];if(value===undefined||value===""||(Array.isArray(value)&&value.length===0)){alert("回答を選択してください");return}if(q.type==="number"&&Number(value)<=0){alert("数値を入力してください");return}if(current<questions.length-1){current++;renderQuestion()}else showResult()});
document.getElementById("retryBtn").addEventListener("click",()=>location.reload());document.getElementById("printBtn").addEventListener("click",()=>window.print());
function renderQuestion(){const q=questions[current];questionTitle.textContent=q.title;questionHelp.textContent=q.help||"";progressText.textContent=`${current+1} / ${questions.length}`;progressBar.style.width=`${((current+1)/questions.length)*100}%`;answerArea.innerHTML="";if(q.type==="number"){const label=document.createElement("label");label.className="answer selected";label.innerHTML=`<input type="number" min="0" step="0.1" value="${answers[q.id]||""}" placeholder="入力"> <span>${q.unit||""}</span>`;const input=label.querySelector("input");input.addEventListener("input",e=>answers[q.id]=e.target.value);answerArea.appendChild(label);setTimeout(()=>input.focus(),50);return}q.options.forEach(opt=>{const label=document.createElement("label");label.className="answer";const inputType=q.type==="multi"?"checkbox":"radio";const checked=q.type==="multi"?(answers[q.id]||[]).includes(opt):answers[q.id]===opt;label.innerHTML=`<input type="${inputType}" name="${q.id}" ${checked?"checked":""}> <span>${opt}</span>`;if(checked)label.classList.add("selected");label.addEventListener("click",e=>{e.preventDefault();if(q.type==="multi"){const arr=answers[q.id]||[];if(arr.includes(opt))answers[q.id]=arr.filter(x=>x!==opt);else{if(q.max&&arr.length>=q.max){alert(`最大${q.max}つまで選べます`);return}answers[q.id]=[...arr,opt]}}else answers[q.id]=opt;renderQuestion()});answerArea.appendChild(label)})}
function calcScores(){const scores=Object.fromEntries(categories.map(c=>[c,0]));questions.forEach(q=>{const ans=answers[q.id];if(!ans||!q.score)return;const values=Array.isArray(ans)?ans:[ans];values.forEach(v=>{const add=q.score[v];if(!add)return;Object.entries(add).forEach(([cat,pts])=>scores[cat]+=pts)})});return scores}
function getPhase(){const h=parseFloat(answers.height),w=parseFloat(answers.weight),bmi=h?w/Math.pow(h/100,2):null,goal=answers.goal,bodySat=answers.bodySatisfaction,parts=answers.parts||[],bmiText=bmi?`BMI：${bmi.toFixed(1)}`:"";if(bmi&&bmi<18.5)return{name:"健康優先期",icon:"🤍",bmiText,text:"現在は減量よりも、栄養バランスや健康的な身体づくりを優先しましょう。体重を落とすより、心と身体を整えることが大切です。"};if(goal==="体重を落としたい"||bodySat==="かなり不満"||bodySat==="少し不満")return{name:"減量期",icon:"🌱",bmiText,text:"現在は体重を落とすことを優先すると、変化を感じやすい時期です。ただし、何から始めるべきかは人によって違います。"};if(goal==="見た目を変えたい"||parts.length>0)return{name:"ボディメイク期",icon:"💪",bmiText,text:"現在は体重だけでなく、姿勢や筋肉を整えることで理想の見た目に近づきやすい時期です。"};return{name:"維持・習慣化期",icon:"🤍",bmiText,text:"現在はリバウンドを防ぎながら、健康的な習慣を続けることが大切な時期です。"}}
function fastingCandidate(){return answers.freeTime==="30分未満"||answers.fail==="結果が出なかった"||answers.fail==="時間がなかった"}
function showResult(){quizScreen.classList.remove("active");resultScreen.classList.add("active");const scores=calcScores(),top=Object.entries(scores).sort((a,b)=>b[1]-a[1]).slice(0,3),phase=getPhase(),ranks=["🥇 第1優先","🥈 第2優先","🥉 第3優先"];let html=`<div class="result-box"><span class="rank">${phase.icon} あなたの現在地</span><h3>${phase.name}</h3><p>${phase.text}</p><p class="bmi">${phase.bmiText}</p></div><div class="result-box"><h3>今のあなたが取り組む順番</h3><p>やることを増やすより、まずは優先順位を絞ることが大切です。</p></div>`;top.forEach(([cat],i)=>{const t=templates[cat];html+=`<div class="result-box"><span class="rank">${ranks[i]}</span><h3>${cat}</h3><p><strong>なぜ？</strong><br>${t.why}</p><p><strong>今日からやること</strong></p><ul>${t.actions.map(x=>`<li>${x}</li>`).join("")}</ul><p><strong>期待できる変化</strong></p><ul>${t.change.map(x=>`<li>${x}</li>`).join("")}</ul><p>${t.message}</p></div>`});if(fastingCandidate())html+=`<div class="result-box"><span class="rank">⭐ 条件付きで検討</span><h3>ファスティング</h3><p>あなたには、短期間で生活をリセットする方法も選択肢の一つになるかもしれません。興味があれば、正しい方法を学んだ上で検討してみましょう。</p><p class="warning">※妊娠中・授乳中・持病がある方、体調に不安がある方は推奨しません。必要に応じて医師や専門家に相談してください。</p></div>`;html+=`<div class="result-box"><span class="rank">90日ロードマップ</span><div class="roadmap"><div class="month"><strong>1ヶ月目</strong><br>${top[0][0]}に集中</div><div class="month"><strong>2ヶ月目</strong><br>${top[1][0]}を追加</div><div class="month"><strong>3ヶ月目</strong><br>${top[2][0]}を追加</div></div></div><div class="result-box"><h3>最後に</h3><p>完璧を目指さなくて大丈夫。今日の診断結果は「今のあなた」に合ったスタート地点です。ライフスタイルが変われば、合う方法も変わります。迷った時は、またここに戻ってきてください。</p></div>`;document.getElementById("resultArea").innerHTML=html;window.scrollTo({top:0,behavior:"smooth"})}
